from __future__ import annotations

import json
from pathlib import Path

from atelier.core.capabilities.default_definitions import build_default_registry
from atelier.core.environment import skill_visible

ROOT = Path(__file__).resolve().parents[2]
PLUGIN = ROOT / "integrations" / "claude" / "plugin"
EXPECTED_MODELS = {
    "code": "claude-opus-4.8",
    "explore": "claude-sonnet-4.6",
    "execute": "claude-opus-4.8",
    "plan": "claude-sonnet-4.6",
    "research": "claude-sonnet-4.6",
    "review": "claude-sonnet-4.6",
    "solve": "claude-opus-4.8",
}
EXPECTED_TURNS = {
    "code": 100,
    "explore": 25,
    "execute": 100,
    "plan": 100,
    "research": 25,
    "review": 40,
    "solve": 80,
}


def _expected_packaged_skills() -> set[str]:
    return {
        path.parent.name
        for path in (ROOT / "integrations" / "skills").glob("*/SKILL.md")
        if skill_visible(path.parent.name)
    }


def _frontmatter(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    assert text.startswith("---\n")
    return text.split("---", 2)[1]


def test_plugin_mcp_server_is_loaded_at_session_start() -> None:
    config = json.loads((PLUGIN / ".mcp.json").read_text(encoding="utf-8"))
    server = config["mcpServers"]["atelier"]
    assert server["type"] == "stdio"
    assert server["alwaysLoad"] is True
    assert server["command"] == "atelier-mcp"
    assert server["args"] == ["--host", "claude"]
    assert server["env"]["CLAUDE_PLUGIN_ROOT"] == "${CLAUDE_PLUGIN_ROOT}"


def test_plugin_no_longer_ships_dev_agent_variants() -> None:
    assert not list((PLUGIN / "agents").glob("*.dev.md"))


def test_plugin_skills_are_packaged_locally() -> None:
    expected = _expected_packaged_skills()
    found = {path.parent.name for path in (PLUGIN / "skills").glob("*/SKILL.md")}
    registry = build_default_registry(ROOT)
    assert set(registry.surfaced_role_ids("shared_skill")) <= expected
    assert expected == found


def test_plugin_agent_set_matches_canonical_registry() -> None:
    registry = build_default_registry(ROOT)
    expected = set(registry.surfaced_role_ids("claude_agent"))
    stable = {path.stem for path in (PLUGIN / "agents").glob("*.md")}

    assert expected == stable
    assert "general" not in expected


def test_generated_host_agents_keep_atelier_wording() -> None:
    registry = build_default_registry(ROOT)

    for role_id in registry.surfaced_role_ids("claude_agent"):
        body = (PLUGIN / "agents" / f"{role_id}.md").read_text(encoding="utf-8")
        assert "Vix" not in body
        assert "Generated by `scripts/sync_agent_context.py`" in body
        assert f"# {role_id.replace('-', ' ').title()} mode" in body


def test_execute_agent_includes_shared_coding_guidelines() -> None:
    body = (PLUGIN / "agents" / "execute.md").read_text(encoding="utf-8")
    assert "## Coding Guidelines" in body


def test_generated_claude_agents_project_turn_defaults_without_pinning_model() -> None:
    for role_id, expected_model in EXPECTED_MODELS.items():
        frontmatter = _frontmatter(PLUGIN / "agents" / f"{role_id}.md")
        assert f"maxTurns: {EXPECTED_TURNS[role_id]}" in frontmatter
        assert f"model: {expected_model}" not in frontmatter
