from __future__ import annotations

import json
from pathlib import Path

from atelier.core.capabilities.default_definitions import build_default_registry

ROOT = Path(__file__).resolve().parents[2]
PLUGIN = ROOT / "integrations" / "claude" / "plugin"


def _frontmatter(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    assert text.startswith("---\n")
    return text.split("---", 2)[1]


def test_plugin_mcp_server_is_loaded_at_session_start() -> None:
    config = json.loads((PLUGIN / ".mcp.json").read_text(encoding="utf-8"))
    server = config["mcpServers"]["atelier"]
    assert server["type"] == "stdio"
    assert server["alwaysLoad"] is True
    assert server["command"] == "atelier-mcp"
    assert server["args"] == ["--host", "claude"]
    assert server["env"]["CLAUDE_PLUGIN_ROOT"] == "${CLAUDE_PLUGIN_ROOT}"


def test_main_agent_dev_variant_bans_native_file_tools() -> None:
    """code.dev.md is the dev-mode agent definition.

    It bans native file tools to enforce use of Atelier MCP equivalents.
    The stable code.md variant keeps native fallback available.
    """
    frontmatter = _frontmatter(PLUGIN / "agents" / "code.dev.md")
    # Native file tools must be banned — enforces Atelier tool use in dev mode
    for tool_name in ["Read", "Edit", "Write", "Grep", "Glob", "NotebookEdit"]:
        assert tool_name in frontmatter
    # Atelier dev tool names must NOT appear in frontmatter (they're in the body)
    assert "mcp__atelier__search" not in frontmatter

    stable = _frontmatter(PLUGIN / "agents" / "code.md")
    assert "disallowedTools" not in stable


def test_explore_agent_is_fast_read_only_and_uses_native_fallback() -> None:
    frontmatter = _frontmatter(PLUGIN / "agents" / "explore.md")
    body = (PLUGIN / "agents" / "explore.md").read_text(encoding="utf-8")
    for tool_name in ["Read", "Grep", "Glob"]:
        assert tool_name in frontmatter
    assert "Edit" in frontmatter
    assert "mcp__atelier__edit" not in frontmatter
    assert "Agent" in frontmatter
    assert "12 tool calls" in body


def test_explore_dev_variant_can_use_mcp_read_search() -> None:
    frontmatter = _frontmatter(PLUGIN / "agents" / "explore.dev.md")
    assert "mcp__atelier__search" in frontmatter
    assert "mcp__atelier__read" in frontmatter


def test_plugin_skills_are_packaged_locally() -> None:
    expected = {
        "code",
        "explore",
        "execute",
        "plan",
        "research",
        "review",
        "solve",
    }
    found = {path.parent.name for path in (PLUGIN / "skills").glob("*/SKILL.md")}
    registry = build_default_registry(ROOT)
    assert expected == set(registry.surfaced_role_ids("shared_skill"))
    assert expected <= found


def test_plugin_agent_set_matches_canonical_registry() -> None:
    registry = build_default_registry(ROOT)
    expected = set(registry.surfaced_role_ids("claude_agent"))
    stable = {path.stem for path in (PLUGIN / "agents").glob("*.md") if not path.name.endswith(".dev.md")}
    dev = {path.name.removesuffix(".dev.md") for path in (PLUGIN / "agents").glob("*.dev.md")}

    assert expected == stable
    assert expected == dev
    assert "general" not in expected


def test_generated_host_agents_keep_atelier_wording() -> None:
    registry = build_default_registry(ROOT)

    for role_id in registry.surfaced_role_ids("claude_agent"):
        body = (PLUGIN / "agents" / f"{role_id}.md").read_text(encoding="utf-8")
        assert "Vix" not in body
        assert "Generated by `scripts/render_mode_surfaces.py`" in body
        assert f"# {role_id.replace('-', ' ').title()} mode" in body
