#!/usr/bin/env bash
# Atelier statusLine script for Claude Code.
# Prints one compact row that fits inside Claude's native agent frame:
#   atelier | Sonnet ctx 50k 35% · ↑ $0.012 (I:30k C:10k O:5k)
#
# The dynamic segment (cost/savings/carry/weekly/monthly/vs-CC) is
# generated by the Python backend (atelier savings --segment) and rotates
# every few seconds so the line stays compact. All formatting lives there.

set -u
input=$(cat)
PLUGIN_LABEL="❯ atelier"

if command -v jq >/dev/null 2>&1; then
  # Use a non-whitespace delimiter so Bash preserves empty fields.
  ATELIER_STATUS_DELIM=$'\037'
  IFS="${ATELIER_STATUS_DELIM}" read -r MODEL PCT COST IN_TOK OUT_TOK CACHE_R CACHE_W SESSION_ID MODEL_ID TRANSCRIPT_PATH <<<"$(printf '%s' "$input" | jq -r '
    [
      (.model.display_name // .model.id // "claude"),
      (.context_window.used_percentage // 0),
      (.cost.total_cost_usd // 0),
      (.context_window.current_usage.input_tokens // 0),
      (.context_window.current_usage.output_tokens // 0),
      (.context_window.current_usage.cache_read_input_tokens // 0),
      (.context_window.current_usage.cache_creation_input_tokens // 0),
      (.session_id // ""),
      (.model.id // .model.display_name // ""),
      (.transcript_path // "")
    ] | map(tostring) | join("")
  ' 2>/dev/null)"
else
  read_field() {
    python3 -c "
import json, sys
try:
    d = json.loads(sys.argv[1] or '{}')
    keys = sys.argv[2].split('.')
    v = d
    for k in keys:
        if isinstance(v, dict):
            v = v.get(k)
        else:
            v = None
            break
    if v is None:
        v = sys.argv[3]
    print(v)
except Exception:
    print(sys.argv[3])
" "$input" "$1" "$2"
  }
  MODEL=$(read_field "model.display_name" "$(read_field "model.id" "claude")")
  MODEL_ID=$(read_field "model.id" "$MODEL")
  PCT=$(read_field "context_window.used_percentage" "0")
  COST=$(read_field "cost.total_cost_usd" "0")
  IN_TOK=$(read_field "context_window.current_usage.input_tokens" "0")
  OUT_TOK=$(read_field "context_window.current_usage.output_tokens" "0")
  CACHE_R=$(read_field "context_window.current_usage.cache_read_input_tokens" "0")
  CACHE_W=$(read_field "context_window.current_usage.cache_creation_input_tokens" "0")
  SESSION_ID=$(read_field "session_id" "")
  TRANSCRIPT_PATH=$(read_field "transcript_path" "")
fi

PCT_INT=${PCT%%.*}
[ -z "$PCT_INT" ] && PCT_INT=0

ATELIER_STATUS_ROOT="${ATELIER_ROOT:-${ATELIER_STORE_ROOT:-${HOME}/.atelier}}"
export ATELIER_STATUS_ROOT
export ATELIER_ROOT="${ATELIER_STATUS_ROOT}"
export ATELIER_STATUS_SESSION_ID="${SESSION_ID:-}"
export ATELIER_STATUS_MODEL="${MODEL_ID:-${MODEL:-}}"
export ATELIER_STATUS_MODEL_DISPLAY="${MODEL:-}"
ATELIER_PY="$(bash "$(dirname "${BASH_SOURCE[0]}")/_atelier_python.sh" 2>/dev/null)"
ATELIER_PY="${ATELIER_PY:-python3}"

# --- Cost reset on /clear ---
# SessionStart(clear) drops two markers:
#   1. Session-keyed: statusline_cost_reset/<session_id>
#   2. Workspace-keyed: statusline_cost_reset/ws_<workspace_key>
# The workspace-keyed marker handles the case where /clear creates a new
# session_id: Claude Code fires SessionStart(clear) with the pre-clear id,
# but the statusline renders with the post-clear id, so the session-keyed
# marker would never be matched without this fallback.
if [ -n "${SESSION_ID:-}" ]; then
  _ATELIER_COST_RESET="${ATELIER_STATUS_ROOT}/statusline_cost_reset/${SESSION_ID}"
  _ATELIER_COST_BASE="${ATELIER_STATUS_ROOT}/statusline_cost_baseline/${SESSION_ID}"
  # Derive workspace key from TRANSCRIPT_PATH. Claude Code names its project
  # dirs by replacing every "/" in the cwd with "-"; the hook writes the
  # marker with the same encoding so we can match it here.
  _ATELIER_COST_RESET_WS=""
  if [ -n "${TRANSCRIPT_PATH:-}" ]; then
    _TR_DIR=$(dirname "${TRANSCRIPT_PATH}" 2>/dev/null || echo "")
    _TR_WS=$(basename "${_TR_DIR}" 2>/dev/null || echo "")
    # Subagent transcripts live one level deeper; skip past the subagents/ dir.
    if [ "${_TR_WS:-}" = "subagents" ]; then
      _TR_DIR=$(dirname "${_TR_DIR}" 2>/dev/null || echo "")
      _TR_WS=$(basename "${_TR_DIR}" 2>/dev/null || echo "")
    fi
    if [ -n "${_TR_WS:-}" ] && [ "${_TR_WS}" != "." ] && [ "${_TR_WS}" != "/" ]; then
      _ATELIER_COST_RESET_WS="${ATELIER_STATUS_ROOT}/statusline_cost_reset/ws_${_TR_WS}"
    fi
  fi
  if [ -f "${_ATELIER_COST_RESET}" ] || { [ -n "${_ATELIER_COST_RESET_WS:-}" ] && [ -f "${_ATELIER_COST_RESET_WS}" ]; }; then
    mkdir -p "${ATELIER_STATUS_ROOT}/statusline_cost_baseline" 2>/dev/null
    printf '%s' "${COST:-0}" >"${_ATELIER_COST_BASE}" 2>/dev/null
    rm -f "${_ATELIER_COST_RESET}" 2>/dev/null
    [ -n "${_ATELIER_COST_RESET_WS:-}" ] && rm -f "${_ATELIER_COST_RESET_WS}" 2>/dev/null
  fi
  if [ -f "${_ATELIER_COST_BASE}" ]; then
    _ATELIER_COST_BASE_VAL=$(cat "${_ATELIER_COST_BASE}" 2>/dev/null)
    COST=$(awk "BEGIN { d=${COST:-0}-${_ATELIER_COST_BASE_VAL:-0}; if (d<0) d=0; printf \"%.6f\", d }" 2>/dev/null || printf '%s' "${COST}")
  fi
fi

# --- ANSI colors ---
if [ -n "${ATELIER_NO_COLOR:-}" ]; then
  C_BRAND=""; C_PIPE=""; C_DIM=""; C_RESET=""
else
  C_BRAND=$'\033[1;38;2;168;85;247m'
  C_PIPE=$'\033[2;38;2;200;200;200m'
  C_DIM=$'\033[2;38;2;200;200;200m'
  C_RESET=$'\033[0m'
fi
PIPE="${C_PIPE}|${C_RESET}"
SEP="${C_DIM}/${C_RESET}"

# Live context occupancy (what fills the window now; drops after /compact).
LIVE_CTX_TOK=$(( ${IN_TOK:-0} + ${CACHE_R:-0} + ${CACHE_W:-0} ))
fmt_ctx() {
  local n=$1
  if [ "$n" -ge 1000000 ] 2>/dev/null; then
    local s=$(( n * 10 / 1000000 ))
    printf '%d.%dM' $(( s / 10 )) $(( s % 10 ))
  elif [ "$n" -ge 1000 ] 2>/dev/null; then
    printf '%dk' $(( n / 1000 ))
  else
    printf '%d' "$n"
  fi
}
ACTUAL_CTX_F=$(fmt_ctx "${LIVE_CTX_TOK}")

# --- Rotating dynamic segment from backend ---
# Export live cost + token counts so the backend can build frame 0.
export ATELIER_STATUSLINE_COST_USD="${COST:-0}"
export ATELIER_STATUSLINE_LIVE_IN_TOK="$(( ${IN_TOK:-0} + ${CACHE_W:-0} ))"
export ATELIER_STATUSLINE_LIVE_CACHE_TOK="${CACHE_R:-0}"
export ATELIER_STATUSLINE_LIVE_OUT_TOK="${OUT_TOK:-0}"
[ -n "${ATELIER_NO_COLOR:-}" ] && export ATELIER_STATUSLINE_NO_COLOR=1

_ATELIER_BIN="$(dirname "${ATELIER_PY}")/atelier"
DYNAMIC_SEG=""
if [ -x "${_ATELIER_BIN}" ]; then
  DYNAMIC_SEG=$("${_ATELIER_BIN}" savings --segment 2>/dev/null)
fi
if [ -z "${DYNAMIC_SEG:-}" ]; then
  DYNAMIC_SEG=$(uv run --quiet atelier savings --segment 2>/dev/null)
fi

# --- Background shell jobs ---
BG_JOBS=0
if [ -n "${TRANSCRIPT_PATH:-}" ] && [ -f "${TRANSCRIPT_PATH}" ]; then
  _BG_SESSION_ROOT="${TRANSCRIPT_PATH%/subagents/*}"
  if [ "${_BG_SESSION_ROOT}" = "${TRANSCRIPT_PATH}" ]; then
    _BG_SESSION_ROOT="$(dirname "${TRANSCRIPT_PATH}")"
  fi
  _BG_SCAN_FILES=()
  while IFS= read -r -d '' _BG_F; do
    _BG_SCAN_FILES+=("${_BG_F}")
  done < <(find "${_BG_SESSION_ROOT}" -maxdepth 2 -type f -name '*.jsonl' -print0 2>/dev/null)
  if [ "${#_BG_SCAN_FILES[@]}" -eq 0 ]; then
    _BG_SCAN_FILES=("${TRANSCRIPT_PATH}")
  fi
  BG_JOBS=$(awk '
    /tool_use_id/ && /Command running in background with ID: / {
      line = $0
      path = ""
      if (match(line, /Output is being written to: [^", ]+/)) {
        path = substr(line, RSTART, RLENGTH)
        sub(/^Output is being written to: /, "", path)
      }
      while (match(line, /Command running in background with ID: [a-z0-9]+/)) {
        id = substr(line, RSTART, RLENGTH)
        sub(/^.*ID: /, "", id)
        launched[id] = 1
        if (path != "") output_file[id] = path
        line = substr(line, RSTART + RLENGTH)
      }
    }
    /task-notification/ && match($0, /<task-id>[a-z0-9]+<\/task-id>/) {
      id = substr($0, RSTART, RLENGTH)
      gsub(/<\/?task-id>/, "", id)
      if ($0 ~ /<status>(completed|failed|stopped|cancelled|killed)<\/status>/) done[id] = 1
    }
    END {
      n = 0
      for (id in launched) {
        if (id in done) continue
        if (!(id in output_file)) continue
        cmd = "test -e \"" output_file[id] "\""
        if (system(cmd) != 0) continue
        n++
      }
      print n
    }
  ' "${_BG_SCAN_FILES[@]}" 2>/dev/null)
  [ -z "${BG_JOBS}" ] && BG_JOBS=0
fi

# --- Background agents ---
BG_AGENTS=0
if [ -n "${SESSION_ID:-}" ]; then
  _NOW_EPOCH=$(date +%s)
  for _TASK_DIR in "${TMPDIR:-/tmp}/claude-$(id -u)"/*/${SESSION_ID}/tasks; do
    [ -d "${_TASK_DIR}" ] || continue
    for _TASK_LNK in "${_TASK_DIR}"/*.output; do
      [ -L "${_TASK_LNK}" ] || continue
      _TASK_MT=$(stat -L -c %Y "${_TASK_LNK}" 2>/dev/null || stat -L -f %m "${_TASK_LNK}" 2>/dev/null) || continue
      [ $(( _NOW_EPOCH - _TASK_MT )) -le 60 ] && BG_AGENTS=$(( BG_AGENTS + 1 ))
    done
    break
  done
fi

TASKS_SEG=""
[ "${BG_JOBS:-0}" -gt 0 ] 2>/dev/null && TASKS_SEG=" ${SEP} ${BG_JOBS} bg"
[ "${BG_AGENTS:-0}" -gt 0 ] 2>/dev/null && TASKS_SEG="${TASKS_SEG} ${SEP} ${BG_AGENTS} agent"

printf '%s%s%s %s %s ctx %s %s%%%s%s\n' \
  "$C_BRAND" "$PLUGIN_LABEL" "$C_RESET" \
  "$PIPE" "$MODEL" "$ACTUAL_CTX_F" "$PCT_INT" \
  "${DYNAMIC_SEG}" "$TASKS_SEG"
