/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e76067d116507a6ff29ab8076c0920de)
interface __BaseEnv_Env {
  DB: D1Database;
  EMAIL: SendEmail;
  SENDPULSE_API_ID: "";
  LICENSE_PUBLIC_KEY: "4W8TlWyl9GWC0Fa2bkzsj4e7i1AMJDtVADq6JgPPmDE=";
  LICENSE_FROM_EMAIL: "licenses@atelier.ws";
  SITE_URL: "https://atelier.ws";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
