#!/usr/bin/env python3
"""Render canonical Atelier mode docs into host agent and skill surfaces."""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from atelier.core.capabilities.default_definitions import (  # noqa: E402
    DefaultRole,
    HostProjection,
    ModeDoc,
    build_default_registry,
    load_mode_docs,
)

CODING_GUIDELINES_PATH = ROOT / "docs" / "agent-os" / "coding-guidelines.md"
CORE_DISCIPLINE_PATH = ROOT / "docs" / "agent-os" / "core-discipline.md"

# Bare ``{{TOKEN}}`` placeholders a mode doc may embed; each expands to a shared
# "## <heading>" section sourced from one canonical partial. A mode opts in by
# including the token anywhere in its body.
SHARED_SECTIONS: dict[str, tuple[str, Path]] = {
    "{{CODING_GUIDELINES}}": ("Coding Guidelines", CODING_GUIDELINES_PATH),
    "{{CORE_DISCIPLINE}}": ("Core discipline", CORE_DISCIPLINE_PATH),
}
HOST_SKILL_DIRS = {
    "claude": ROOT / "integrations" / "claude" / "plugin" / "skills",
    "codex": ROOT / "integrations" / "codex" / "plugin" / "skills",
    "antigravity": ROOT / "integrations" / "antigravity" / "skills",
}


def generated_notice(output_path: Path, source_path: Path) -> str:
    _ = (output_path, source_path)
    return (
        "<!-- Generated by `scripts/render_mode_surfaces.py`. "
        "Distribution artifact: do not edit directly; regenerate from repository sources. -->"
    )


def markdown_body(path: Path) -> str:
    text = path.read_text(encoding="utf-8").strip()
    lines = text.splitlines()
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
        while lines and not lines[0].strip():
            lines = lines[1:]
    return "\n".join(lines).rstrip()


def _shared_section(heading: str, source_path: Path) -> str:
    return "\n".join([f"## {heading}", "", markdown_body(source_path)])


def render_mode_body(mode_doc: ModeDoc) -> str:
    body = mode_doc.body.rstrip()
    for token, (heading, source_path) in SHARED_SECTIONS.items():
        if token in body:
            body = body.replace(token, _shared_section(heading, source_path))
    return body


def _format_frontmatter_value(value: Any) -> str:
    if isinstance(value, list):
        return json.dumps(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def render_frontmatter(items: list[tuple[str, Any]]) -> str:
    lines = ["---"]
    for key, value in items:
        lines.append(f"{key}: {_format_frontmatter_value(value)}")
    lines.append("---")
    return "\n".join(lines)


def _inject_description(frontmatter: tuple[tuple[str, Any], ...], description: str) -> list[tuple[str, Any]]:
    rendered: list[tuple[str, Any]] = []
    for key, value in frontmatter:
        rendered.append((key, description if key == "description" and value == "" else value))
    return rendered


def render_skill(role: DefaultRole, mode_doc: ModeDoc, output_path: Path) -> str:
    return (
        "\n".join(
            [
                render_frontmatter([("name", role.role_id), ("description", role.skill_description)]),
                "",
                generated_notice(output_path, ROOT / mode_doc.source_path),
                "",
                render_mode_body(mode_doc),
            ]
        ).rstrip()
        + "\n"
    )


def render_claude_agent(
    role: DefaultRole,
    mode_doc: ModeDoc,
    output_path: Path,
    projection: HostProjection,
) -> str:
    frontmatter = _inject_description(projection.frontmatter, role.agent_description)
    identity_block = ["You are operating as *atelier:code*.", ""] if role.role_id == "code" else []
    return (
        "\n".join(
            [
                render_frontmatter(frontmatter),
                "",
                generated_notice(output_path, ROOT / mode_doc.source_path),
                "",
                *identity_block,
                render_mode_body(mode_doc),
            ]
        ).rstrip()
        + "\n"
    )


def render_simple_agent(
    role: DefaultRole,
    mode_doc: ModeDoc,
    output_path: Path,
    projection: HostProjection,
) -> str:
    identity_block = ["You are operating as *atelier:code*.", ""] if role.role_id == "code" else []
    return (
        "\n".join(
            [
                render_frontmatter(list(projection.frontmatter)),
                "",
                generated_notice(output_path, ROOT / mode_doc.source_path),
                "",
                *identity_block,
                render_mode_body(mode_doc),
            ]
        ).rstrip()
        + "\n"
    )


def build_mode_outputs(root: Path | None = None) -> dict[Path, str]:
    repo_root = ROOT if root is None else root
    registry = build_default_registry(repo_root)
    mode_docs = load_mode_docs(repo_root)
    outputs: dict[Path, str] = {}

    for role_id in registry.surfaced_role_ids("shared_skill"):
        role = registry.roles[role_id]
        mode_doc = mode_docs[role_id]

        skill_path = repo_root / "integrations" / "skills" / role_id / "SKILL.md"
        skill_content = render_skill(role, mode_doc, skill_path)
        outputs[skill_path] = skill_content
        for host_dir in HOST_SKILL_DIRS.values():
            host_skill_path = host_dir / role_id / "SKILL.md"
            outputs[host_skill_path] = skill_content

        stable_projection = registry.projection(role_id, "claude_agent")
        stable_path = (
            repo_root / "integrations" / "claude" / "plugin" / "agents" / f"{stable_projection.output_name}.md"
        )
        outputs[stable_path] = render_claude_agent(role, mode_doc, stable_path, stable_projection)

        dev_projection = registry.projection(role_id, "claude_agent_dev")
        dev_path = repo_root / "integrations" / "claude" / "plugin" / "agents" / f"{dev_projection.output_name}.md"
        outputs[dev_path] = render_claude_agent(role, mode_doc, dev_path, dev_projection)

        antigravity_projection = registry.projection(role_id, "antigravity_agent")
        antigravity_path = (
            repo_root
            / "integrations"
            / "antigravity"
            / "plugin"
            / "agents"
            / f"{antigravity_projection.output_name}.md"
        )
        outputs[antigravity_path] = render_simple_agent(
            role,
            mode_doc,
            antigravity_path,
            antigravity_projection,
        )

        opencode_projection = registry.projection(role_id, "opencode_agent")
        opencode_path = repo_root / "integrations" / "opencode" / "agents" / f"{opencode_projection.output_name}.md"
        outputs[opencode_path] = render_simple_agent(role, mode_doc, opencode_path, opencode_projection)

    for output_path, content in outputs.items():
        if "{{" in content:
            raise ValueError(f"unexpanded template token in generated surface: {output_path}")
    return outputs


def write_or_diff(path: Path, expected: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == expected:
        return False
    if check:
        diff = difflib.unified_diff(
            current.splitlines(),
            expected.splitlines(),
            fromfile=str(path),
            tofile=f"{path} (generated)",
            lineterm="",
        )
        sys.stdout.write("\n".join(diff) + "\n")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated outputs differ")
    args = parser.parse_args()

    changed = False
    for path, content in build_mode_outputs().items():
        changed = write_or_diff(path, content, check=args.check) or changed

    if args.check and changed:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
