#!/usr/bin/env python3
"""Generate host instruction surfaces from the live Agent OS docs."""

from __future__ import annotations

# ruff: noqa: E402
import argparse
import difflib
import json
import os
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from atelier.core.capabilities.default_definitions import (
    DefaultRole,
    HostProjection,
    ModeDoc,
    build_default_registry,
    load_mode_docs,
)
from atelier.core.capabilities.model_settings import (
    CANONICAL_COPILOT_AGENT_MODEL,
    resolve_host_model,
)
from atelier.core.capabilities.workspace_host_overrides import (
    rewrite_agent_model,
)
from atelier.core.environment import skill_visible

_AGENT_DISPLAY_ORDER = ("code", "explore", "plan", "execute", "research", "review", "solve")
_CLAUDE_ROLE_SKILL_IDS = frozenset(_AGENT_DISPLAY_ORDER)

DOC_LINKS = [
    ("Agent OS", ROOT / "docs/agent-os/README.md"),
    ("Workflow", ROOT / "docs/agent-os/workflow.md"),
    ("Taste invariants", ROOT / "docs/agent-os/taste-invariants.md"),
    ("Coding guidelines", ROOT / "docs/agent-os/coding-guidelines.md"),
    ("Validation matrix", ROOT / "docs/agent-os/validation-matrix.md"),
    ("Architecture", ROOT / "docs/architecture/README.md"),
    ("Quality scorecard", ROOT / "docs/quality/scorecard.md"),
    ("Plans", ROOT / "docs/plans/README.md"),
    ("Decisions", ROOT / "docs/decisions/README.md"),
]
CODING_GUIDELINES_PATH = ROOT / "docs/agent-os/coding-guidelines.md"
CORE_DISCIPLINE_PATH = ROOT / "docs/agent-os/core-discipline.md"

# Bare ``{{TOKEN}}`` placeholders a mode doc may embed; each expands to a shared
# "## <heading>" section sourced from one canonical partial. A mode opts in by
# including the token anywhere in its body.
SHARED_SECTIONS: dict[str, tuple[str, Path]] = {
    "{{CODING_GUIDELINES}}": ("Coding Guidelines", CODING_GUIDELINES_PATH),
    "{{CORE_DISCIPLINE}}": ("Core discipline", CORE_DISCIPLINE_PATH),
}
HOST_SKILL_DIRS = {
    "claude": ROOT / "integrations" / "claude" / "plugin" / "skills",
    "codex": ROOT / "integrations" / "codex" / "plugin" / "skills",
    "antigravity": ROOT / "integrations" / "antigravity" / "skills",
}

HOST_FALLBACKS = {
    "copilot": "Copilot or VS Code native file reads, workspace search, shell `rg`, or `grep`",
    "antigravity": "Antigravity or agy native file reads, workspace search, shell `rg`, or `grep`",
    "claude": "Claude-native file tools, Grep/Glob, shell `rg`, or `grep`",
    "codex": "native Codex file reads, shell `rg`, `grep`, or direct repository search",
    "opencode": "opencode-native file reads, repository search, shell `rg`, or `grep`",
    "cursor": "Cursor or VS Code native file reads, workspace search, shell `rg`, or `grep`",
    "hermes": "native Hermes file tools, shell `rg`, `grep`, or direct repository search",
}

HOST_DISPLAY = {
    "antigravity": "Antigravity",
    "copilot": "Copilot",
    "claude": "Claude",
    "codex": "Codex",
    "opencode": "OpenCode",
    "cursor": "Cursor",
    "hermes": "Hermes",
}

SESSION_TEMPLATE = (
    "Atelier budget optimizer is active for {host}.\n"
    "Use Atelier MCP tools first for file I/O, search, edits, and shell work.\n"
    "Always prefer Atelier MCP tools for file I/O, search, edits, shell, and code-intel work.\n"
    "Use native host tools only when Atelier returns `noop`, is hidden, or is unavailable.\n"
    "Before changing files, name the deliverable and summarize the smallest viable plan.\n"
    "Keep context narrow: use only the current goal, relevant files, failing command/output, and known constraints.\n"
    "Restate working context in under 10 bullets before editing or after compaction.\n"
    "If more than 10 minutes pass without an edit, name the expected deliverable or check with the user.\n"
    "If the same approach fails twice, change approach; do not retry a third time.\n"
)


def relpath(output_path: Path, target: Path) -> str:
    return os.path.relpath(target, output_path.parent)


def generated_notice(output_path: Path) -> str:
    source = relpath(output_path, ROOT / "docs/agent-os/README.md")
    docs_dir = relpath(output_path, ROOT / "docs/agent-os")
    return (
        "<!-- Generated by `scripts/sync_agent_context.py`. "
        f"Edit `{source}` and the linked docs under `{docs_dir}/`, then rerun the generator. -->"
    )


def distribution_notice() -> str:
    return (
        "<!-- Generated by `scripts/sync_agent_context.py`. "
        "Distribution artifact: do not edit directly; regenerate from repository sources. -->"
    )


def doc_links(output_path: Path) -> str:
    return "\n".join(f"- [{label}]({relpath(output_path, target)})" for label, target in DOC_LINKS)


def budget_section() -> str:
    return "\n".join(
        [
            "## Budget optimizer",
            "",
            "- Before changing files, name the deliverable and summarize the smallest viable plan.",
            "- Keep context narrow: use only the current goal, relevant files, failing command/output, and known constraints.",
            "- Restate working context in under 10 bullets before editing or after compaction.",
            "- If more than 10 minutes pass without an edit, name the expected deliverable or check with the user.",
            "- If the same approach fails twice, change approach; do not retry a third time.",
        ]
    )


def fallback_section(host: str) -> str:
    return "\n".join(
        [
            "## Native fallback",
            "",
            f"If an Atelier MCP tool returns `noop`, is hidden, or is unavailable, use {HOST_FALLBACKS[host]}.",
            "Always return findings instead of waiting for tool availability to improve.",
        ]
    )


def validation_line(output_path: Path) -> str:
    matrix = relpath(output_path, ROOT / "docs/agent-os/validation-matrix.md")
    return f"See [Validation matrix]({matrix}) for the minimum checks by change surface."


def _markdown_body(path: Path) -> str:
    text = path.read_text(encoding="utf-8").strip()
    lines = text.splitlines()
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
        while lines and not lines[0].strip():
            lines = lines[1:]
    return "\n".join(lines).rstrip()


def coding_guidelines_section() -> str:
    return "\n".join(["## Coding Guidelines", "", _markdown_body(CODING_GUIDELINES_PATH)])


_OPENCODE_TOOL_PREFIX = "atelier_"


def _tn(name: str, *, prefix: str = "") -> str:
    """Return a tool name, optionally prefixed with *atelier_*."""
    return f"{prefix}{name}"


def tool_substitution_table(*, tool_prefix: str = "") -> str:
    p = tool_prefix
    return "\n".join(
        [
            "## Tool substitution — mandatory",
            "",
            f"- Shared docs use plain tool names like `{_tn('read', prefix=p)}`, `{_tn('search', prefix=p)}`, `{_tn('grep', prefix=p)}`, and `{_tn('edit', prefix=p)}`.",
            "- Some hosts expose the same tools as handles like `mcp__atelier__context`; use the name shown by your host when invoking one explicitly.",
            f"- `{_tn('read', prefix=p)}` for file reads; `{_tn('search', prefix=p)}` / `{_tn('grep', prefix=p)}` for discovery; `{_tn('edit', prefix=p)}` for file changes.",
            f"- `{_tn('symbols', prefix=p)}` / `{_tn('node', prefix=p)}` / `{_tn('callers', prefix=p)}` / `{_tn('usages', prefix=p)}` / `{_tn('explore', prefix=p)}` for code intelligence.",
            f"- `{_tn('shell', prefix=p)}` only for commands without a better Atelier equivalent.",
        ]
    )


def mcp_priority_section(*, tool_prefix: str = "") -> str:
    p = tool_prefix
    lines = [
        "## Always prefer Atelier MCP tools",
        "",
        f"- Prefer Atelier tools (`{_tn('read', prefix=p)}`, `{_tn('edit', prefix=p)}`, `{_tn('shell', prefix=p)}`, etc.) for file I/O, search, edits, shell, and code intelligence.",
        f"- Use `{_tn('symbols', prefix=p)}`/`{_tn('callers', prefix=p)}`/`{_tn('usages', prefix=p)}` before text search when you need code relationships.",
        "- Use native host tools only when the Atelier equivalent returns `noop`, is hidden, or is unavailable.",
    ]
    if tool_prefix:
        lines.append(
            "- Native tools (`bash`, `edit`, `glob`, `grep`, `read`, `webfetch`, `write`) are disallowed by policy — always use the Atelier MCP counterparts."
        )
    return "\n".join(lines)


def distribution_sections(host: str | None = None, *, tool_prefix: str = "") -> list[str]:
    lines = [
        "## Operating loop",
        "",
        "1. **Understand**: Read the relevant source of truth before changing anything; ground every change in real code.",
        f"2. **Implement**: Use Atelier MCP tools (`{_tn('read', prefix=tool_prefix)}`, `{_tn('edit', prefix=tool_prefix)}`, `{_tn('shell', prefix=tool_prefix)}`, etc.) for file I/O, search, edits, and shell work. Use native host tools only when Atelier returns `noop`, is hidden, or is unavailable. If the same approach fails twice, change approach — do not retry a third time.",
        "",
        tool_substitution_table(tool_prefix=tool_prefix),
        "",
        mcp_priority_section(tool_prefix=tool_prefix),
        "",
        budget_section(),
        "",
        coding_guidelines_section(),
    ]
    if host is not None:
        lines.extend(["", fallback_section(host)])
    return lines


def implement_line(output_path: Path) -> str:
    tool_sub_link = relpath(output_path, ROOT / "docs/agent-os/tool-substitution.md")
    return (
        "2. **Implement**: Use Atelier MCP tools for file I/O, search, edits, and shell work "
        f"(see [Tool substitution]({tool_sub_link})). Use native host tools only when Atelier "
        "returns `noop`, is hidden, or is unavailable. If the same approach fails twice, change "
        "approach — do not retry a third time."
    )


def render_project_entrypoint(output_path: Path, *, title: str, host: str | None = None) -> str:
    tool_sub_link = relpath(output_path, ROOT / "docs/agent-os/tool-substitution.md")
    coding_guidelines_link = relpath(output_path, CODING_GUIDELINES_PATH)
    lines = [
        generated_notice(output_path),
        "",
        f"# {title}",
        "",
        "This file is a thin entrypoint. The live source of truth lives in the linked docs tree:",
        "",
        doc_links(output_path),
        "",
        "## Operating loop",
        "",
        "1. **Understand** — read the relevant source of truth before touching any file; ground every change in real code.",
        "2. **Implement** — use Atelier tools for ALL file I/O and shell ops "
        f"(see [Tool substitution]({tool_sub_link})). If the same approach fails twice, change "
        "approach — do not retry a third time.",
        "",
        tool_substitution_table(),
        "",
        mcp_priority_section(),
        "",
        "## Project-specific invariants",
        "",
        "- Verify source-of-truth files before coding instead of guessing shapes.",
        "- Keep root host files short and move durable rules into `docs/agent-os/`.",
        "- Use the validation matrix before concluding the task.",
        "- Promote durable process changes into plans, decisions, or generated host artifacts.",
        "",
        budget_section(),
        "",
        f"Shared coding guidance is sourced from [coding-guidelines.md]({coding_guidelines_link}).",
        "",
        coding_guidelines_section(),
    ]
    if host:
        lines.extend(["", fallback_section(host)])
    lines.extend(["", "## Validation", "", validation_line(output_path)])
    body = "\n".join(lines).rstrip() + "\n"
    if output_path == ROOT / "AGENTS.md":
        return "\n".join(["<!-- ATELIER:CODE START -->", body.rstrip(), "<!-- ATELIER:CODE END -->"]) + "\n"
    return body


def render_copilot_body(output_path: Path) -> str:
    """Thin in-repo version — for .github/copilot-instructions.md where docs/ exists."""
    tool_sub_link = relpath(output_path, ROOT / "docs/agent-os/tool-substitution.md")
    coding_guidelines_link = relpath(output_path, CODING_GUIDELINES_PATH)
    return (
        "\n".join(
            [
                generated_notice(output_path),
                "",
                "## Atelier - Copilot Instructions",
                "",
                "Use the Atelier process for every task:",
                "1. **Understand**: read the relevant source of truth first; ground every change in real code.",
                f"2. **Implement**: use Atelier MCP tools for file I/O, search, edits, and shell work "
                f"(see [Tool substitution]({tool_sub_link})). Use native Copilot or VS Code tools only when Atelier returns `noop`, is hidden, or is unavailable. "
                "If the same approach fails twice, change approach — do not retry a third time.",
                "",
                tool_substitution_table(),
                "",
                mcp_priority_section(),
                "",
                "Treat this file as a thin entrypoint. The live source of truth is:",
                "",
                doc_links(output_path),
                "",
                f"Follow [Coding guidelines]({coding_guidelines_link}) for the exact shared block.",
                "",
                budget_section(),
                "",
                fallback_section("copilot"),
                "",
                "## Validation",
                "",
                f"{validation_line(output_path)} Use the VS Code tasks for repeatable preflight, worktree, and runtime evidence loops.",
            ]
        ).rstrip()
        + "\n"
    )


def render_copilot_user_surface(output_path: Path) -> str:
    """Self-contained distribution surface for Copilot installs."""
    return (
        "\n".join(
            [
                distribution_notice(),
                "",
                "## Atelier - Copilot Instructions",
                "",
                *distribution_sections("copilot"),
            ]
        ).rstrip()
        + "\n"
    )


def render_copilot_workspace(output_path: Path) -> str:
    body = render_copilot_body(output_path)
    return "\n".join(["---", 'applyTo: "**"', "---", "", body]).rstrip() + "\n"


def _copilot_native_tools(role_id: str) -> list[str]:
    base = [
        "atelier/*",
        "search/codebase",
        "web/fetch",
        "findTestFiles",
        "web/githubRepo",
        "read/problems",
        "read/getTaskOutput",
        "search",
        "searchResults",
        "read/terminalLastCommand",
        "read/terminalSelection",
        "search/usages",
        "vscode/vscodeAPI",
    ]
    if role_id in {"code", "execute", "solve"}:
        base[1:1] = [
            "changes",
            "edit/editFiles",
            "execute/getTerminalOutput",
            "execute/runInTerminal",
            "execute/createAndRunTask",
            "execute/runTask",
            "execute/runTests",
            "execute/testFailure",
        ]
    return base


def render_copilot_agent(role: DefaultRole, mode_doc: ModeDoc, projection: HostProjection) -> str:
    tools = "\n".join(f'    "{tool}",' for tool in _copilot_native_tools(role.role_id))
    return (
        "\n".join(
            [
                "---",
                f'description: "{role.agent_description}"',
                f"model: {CANONICAL_COPILOT_AGENT_MODEL}",
                "tools:",
                "  [",
                tools,
                "  ]",
                "---",
                "",
                generated_notice(ROOT / "integrations" / "copilot" / "agents" / f"{projection.output_name}.agent.md"),
                "",
                f"# atelier:{role.role_id}",
                "",
                f"You are operating as *atelier:{role.role_id}*.",
                "",
                render_mode_body(mode_doc),
            ]
        ).rstrip()
        + "\n"
    )


def render_cursor_coding_rules() -> str:
    return (
        "\n".join(
            [
                "---",
                "description: Behavioral guidelines to reduce common LLM coding mistakes."
                " Use when writing, reviewing, or refactoring code to avoid overcomplication,"
                " make surgical changes, surface assumptions, and define verifiable success criteria.",
                "alwaysApply: true",
                "---",
                "",
                coding_guidelines_section().strip(),
            ]
        ).rstrip()
        + "\n"
    )


def render_cursor_role_rule(role: DefaultRole, mode_doc: ModeDoc) -> str:
    return (
        "\n".join(
            [
                "---",
                f"description: Atelier {role.role_id} mode reference for Cursor.",
                "---",
                "",
                render_mode_body(mode_doc),
            ]
        ).rstrip()
        + "\n"
    )


def render_host_surface(output_path: Path, *, title: str, host: str) -> str:
    tool_prefix = _OPENCODE_TOOL_PREFIX if host == "opencode" else ""
    lines = [
        distribution_notice(),
        "",
        f"# {title}",
        "",
        "You are operating as *atelier:code*.",
        "",
        *distribution_sections(host, tool_prefix=tool_prefix),
    ]
    if host == "opencode":
        return (
            "\n".join(
                [
                    "---",
                    "description: Atelier - main coding agent for the Agent Reasoning Runtime",
                    "mode: primary",
                    "---",
                    "",
                    *lines,
                ]
            ).rstrip()
            + "\n"
        )
    return "\n".join(lines).rstrip() + "\n"


def render_distribution_guide(output_path: Path) -> str:
    return (
        "\n".join(
            [
                distribution_notice(),
                "",
                "# Atelier Agent Guide",
                "",
                "This is the compact shared guidance shipped with the Atelier distribution package.",
                "Use a host-specific wrapper when one exists; otherwise this file is the fallback shared guide.",
                "",
                *distribution_sections(),
            ]
        ).rstrip()
        + "\n"
    )


def sync_host_configs() -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for host in ("claude", "codex", "copilot", "antigravity", "opencode", "cursor", "hermes"):
        path = ROOT / "src/atelier/gateway/hosts/configs" / f"{host}.yaml"
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        templates = data.get("prompt_templates", [])
        for item in templates:
            if item.get("name") == "session-optimization":
                item["template"] = SESSION_TEMPLATE.format(host=HOST_DISPLAY[host]).rstrip()
        outputs[path] = yaml.safe_dump(data, sort_keys=False, allow_unicode=False)
    return outputs


def _shared_section(heading: str, source_path: Path) -> str:
    return "\n".join([f"## {heading}", "", _markdown_body(source_path)])


def render_mode_body(mode_doc: ModeDoc) -> str:
    body = mode_doc.body.rstrip()
    for token, (heading, source_path) in SHARED_SECTIONS.items():
        if token in body:
            body = body.replace(token, _shared_section(heading, source_path))
    return body


def _format_frontmatter_value(value: Any) -> str:
    if isinstance(value, (list, dict)):
        return json.dumps(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def render_frontmatter(items: list[tuple[str, Any]]) -> str:
    lines = ["---"]
    for key, value in items:
        lines.append(f"{key}: {_format_frontmatter_value(value)}")
    lines.append("---")
    return "\n".join(lines)


def _inject_description(frontmatter: tuple[tuple[str, Any], ...], description: str) -> list[tuple[str, Any]]:
    rendered: list[tuple[str, Any]] = []
    for key, value in frontmatter:
        rendered.append((key, description if key == "description" and value == "" else value))
    return rendered


def render_skill(role: DefaultRole, mode_doc: ModeDoc) -> str:
    return (
        "\n".join(
            [
                render_frontmatter([("name", role.role_id), ("description", role.skill_description)]),
                "",
                distribution_notice(),
                "",
                render_mode_body(mode_doc),
            ]
        ).rstrip()
        + "\n"
    )


def render_claude_agent(role: DefaultRole, mode_doc: ModeDoc, projection: HostProjection) -> str:
    frontmatter = _inject_description(projection.frontmatter, role.agent_description)
    identity_block = ["You are operating as *atelier:code*.", ""] if role.role_id == "code" else []
    return (
        "\n".join(
            [
                render_frontmatter(frontmatter),
                "",
                distribution_notice(),
                "",
                *identity_block,
                render_mode_body(mode_doc),
            ]
        ).rstrip()
        + "\n"
    )


def render_simple_agent(role: DefaultRole, mode_doc: ModeDoc, projection: HostProjection) -> str:
    identity_block = ["You are operating as *atelier:code*.", ""] if role.role_id == "code" else []
    return (
        "\n".join(
            [
                render_frontmatter(list(projection.frontmatter)),
                "",
                distribution_notice(),
                "",
                *identity_block,
                render_mode_body(mode_doc),
            ]
        ).rstrip()
        + "\n"
    )


def render_opencode_agent(role: DefaultRole, mode_doc: ModeDoc, projection: HostProjection) -> str:
    """OpenCode agent that uses ``atelier_``-prefixed tool names.

    OpenCode registers MCP tools with the ``atelier_`` prefix (``atelier_read``,
    ``atelier_edit``, etc.), so the body must reference those names rather than
    the bare tool names used in other hosts.
    """
    p = _OPENCODE_TOOL_PREFIX
    identity_block = ["You are operating as *atelier:code*.", ""] if role.role_id == "code" else []
    tool_discipline = "\n".join(
        [
            "## OpenCode tool discipline",
            "",
            f"- Shared docs use plain tool names like `{p}read`, `{p}search`, `{p}grep`, and `{p}edit`.",
            f"- In OpenCode, Atelier MCP tools use the `{p}` prefix: `{p}read` for file reads,",
            f"  `{p}edit` for edits, `{p}grep` / `{p}search` for discovery, `{p}shell` for shell,",
            f"  `{p}symbols` / `{p}node` / `{p}callers` / `{p}usages` / `{p}explore` for code intelligence.",
            "- Native OpenCode tools (`bash`, `edit`, `glob`, `grep`, `read`, `webfetch`, `write`)",
            "  are disallowed by policy — always use the Atelier MCP counterparts.",
            "- If an Atelier MCP tool returns `noop`, is hidden, or is unavailable, use",
            "  OpenCode-native file reads, repository search, shell `rg`, or `grep`.",
        ]
    )
    return (
        "\n".join(
            [
                render_frontmatter(list(projection.frontmatter)),
                "",
                distribution_notice(),
                "",
                *identity_block,
                render_mode_body(mode_doc),
                "",
                tool_discipline,
            ]
        ).rstrip()
        + "\n"
    )


def _extra_shared_skill_paths(repo_root: Path, generated_role_ids: set[str]) -> dict[str, Path]:
    skills_root = repo_root / "integrations" / "skills"
    extras: dict[str, Path] = {}
    if not skills_root.exists():
        return extras
    for skill_dir in sorted(skills_root.iterdir()):
        skill_path = skill_dir / "SKILL.md"
        if not skill_dir.is_dir() or not skill_path.is_file():
            continue
        if skill_dir.name in generated_role_ids:
            continue
        if not skill_visible(skill_dir.name):
            continue
        extras[skill_dir.name] = skill_path
    return extras


def build_mode_outputs(root: Path | None = None) -> dict[Path, str]:
    repo_root = ROOT if root is None else root
    registry = build_default_registry(repo_root)
    mode_docs = load_mode_docs(repo_root)
    outputs: dict[Path, str] = {}
    generated_role_ids = set(registry.surfaced_role_ids("shared_skill"))

    for role_id in sorted(generated_role_ids):
        role = registry.roles[role_id]
        mode_doc = mode_docs[role_id]

        skill_path = repo_root / "integrations" / "skills" / role_id / "SKILL.md"
        skill_content = render_skill(role, mode_doc)
        outputs[skill_path] = skill_content
        for host_name, host_dir in HOST_SKILL_DIRS.items():
            if host_name == "claude" and role_id in _CLAUDE_ROLE_SKILL_IDS:
                continue
            host_skill_path = host_dir / role_id / "SKILL.md"
            outputs[host_skill_path] = skill_content

        stable_projection = registry.projection(role_id, "claude_agent")
        stable_path = (
            repo_root / "integrations" / "claude" / "plugin" / "agents" / f"{stable_projection.output_name}.md"
        )
        outputs[stable_path] = render_claude_agent(role, mode_doc, stable_projection)

        antigravity_projection = registry.projection(role_id, "antigravity_agent")
        antigravity_path = (
            repo_root
            / "integrations"
            / "antigravity"
            / "plugin"
            / "agents"
            / f"{antigravity_projection.output_name}.md"
        )
        outputs[antigravity_path] = render_simple_agent(role, mode_doc, antigravity_projection)

        opencode_projection = registry.projection(role_id, "opencode_agent")
        opencode_path = repo_root / "integrations" / "opencode" / "agents" / f"{opencode_projection.output_name}.md"
        outputs[opencode_path] = render_opencode_agent(role, mode_doc, opencode_projection)

        copilot_projection = registry.projection(role_id, "copilot_agent")
        copilot_path = repo_root / "integrations" / "copilot" / "agents" / f"{copilot_projection.output_name}.agent.md"
        outputs[copilot_path] = render_copilot_agent(role, mode_doc, copilot_projection)

        cursor_path = repo_root / "integrations" / "cursor" / "rules" / f"atelier.{role_id}.mdc"
        outputs[cursor_path] = render_cursor_role_rule(role, mode_doc)

    for skill_name, skill_path in _extra_shared_skill_paths(repo_root, generated_role_ids).items():
        content = skill_path.read_text(encoding="utf-8")
        for host_dir in HOST_SKILL_DIRS.values():
            host_skill_path = host_dir / skill_name / "SKILL.md"
            outputs[host_skill_path] = content

    for output_path, content in outputs.items():
        if "{{" in content:
            raise ValueError(f"unexpanded template token in generated surface: {output_path}")
    return outputs


def _role_model_summary(registry: Any) -> str:
    grouped: dict[str, list[str]] = {}
    for role_id in _AGENT_DISPLAY_ORDER:
        model = registry.roles[role_id].model_default
        grouped.setdefault(model, []).append(role_id)
    parts = []
    for model, role_ids in grouped.items():
        labels = ", ".join(f"`{role_id}`" for role_id in role_ids)
        parts.append(f"{labels} use **`{model}`**")
    return "; ".join(parts)


def render_agents_overview(output_path: Path) -> str:
    """Generate the agent/skill comparison surface from the canonical registry."""
    registry = build_default_registry(ROOT)
    rows: list[str] = []
    agent_lines: list[str] = []
    skill_lines: list[str] = []
    for role_id in _AGENT_DISPLAY_ORDER:
        role = registry.roles[role_id]
        projection = registry.projection(role_id, "claude_agent")
        disallowed = next((value for key, value in projection.frontmatter if key == "disallowedTools"), [])
        denies = ", ".join(role.tool_policy.denied_actions) or "—"
        disallowed_text = ", ".join(f"`{tool}`" for tool in disallowed)
        rows.append(
            f"| `{role_id}` | `{role.model_default}` | {role.effort_default} | {role.max_turns} | {role.max_tokens:,} | "
            f"{role.read_mode_hint} | {denies} | {disallowed_text} |"
        )
        agent_lines.append(f"- **`atelier:{role_id}`** — {role.agent_description}")
        skill_lines.append(f"- **`/{role_id}`** — {role.skill_description}")
    lines = [
        generated_notice(output_path),
        "",
        "# Atelier Agents & Skills",
        "",
        "Seven canonical roles, declared once in `src/atelier/core/capabilities/default_definitions.py` and "
        "generated into every host (Claude agents, OpenCode, Antigravity, and shared skills). Each role's full "
        "behavior body lives in [`modes/`](modes/); the agent and its matching `/`-skill share that body.",
        "",
        f"Role defaults are workload-aware: {_role_model_summary(registry)}. These registry defaults feed owned-"
        "runtime fallback and routing; generated Claude host agents inherit the host-selected model and only "
        "project `maxTurns` into frontmatter, while the generated Copilot agent is pinned to `gpt-5.4`. The "
        "`disallowedTools` deny-list is derived from each role's tool policy: every role forces MCP-grounded file "
        "I/O (native `Read`/`Edit`/`Write`/`Grep`/`Glob` are denied); read-only roles additionally lose mutation "
        "(`mcp__atelier__edit`) and sub-agent spawning (`Agent`); **shell is never denied**.",
        "",
        "## Comparison",
        "",
        "| Role | Model | Effort | Max turns | Max tokens | Read mode | Policy denies | Claude `disallowedTools` |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
        *rows,
        "",
        "## Agents",
        "",
        *agent_lines,
        "",
        "## Skills",
        "",
        "Each role is also a `/`-skill with the same body and a `Switch to …` description:",
        "",
        *skill_lines,
    ]
    return "\n".join(lines).rstrip() + "\n"


def build_outputs() -> dict[Path, str]:
    registry = build_default_registry(ROOT)
    mode_outputs = build_mode_outputs(ROOT)
    outputs = {
        ROOT / "AGENTS.md": render_project_entrypoint(ROOT / "AGENTS.md", title="Project Instructions: Atelier"),
        ROOT / "docs/agent-os/agents.md": render_agents_overview(ROOT / "docs/agent-os/agents.md"),
        ROOT / ".github/copilot-instructions.md": render_copilot_workspace(ROOT / ".github/copilot-instructions.md"),
        ROOT / "integrations/AGENTS.atelier.md": render_distribution_guide(ROOT / "integrations/AGENTS.atelier.md"),
        ROOT
        / "integrations/copilot/COPILOT_INSTRUCTIONS.atelier.md": render_copilot_user_surface(
            ROOT / "integrations/copilot/COPILOT_INSTRUCTIONS.atelier.md"
        ),
        ROOT
        / "integrations/claude/AGENTS.atelier.md": render_host_surface(
            ROOT / "integrations/claude/AGENTS.atelier.md",
            title="Atelier Agent Persona",
            host="claude",
        ),
        ROOT
        / "integrations/codex/AGENTS.atelier.md": render_host_surface(
            ROOT / "integrations/codex/AGENTS.atelier.md",
            title="Atelier - Codex Agent",
            host="codex",
        ),
        ROOT
        / "integrations/antigravity/AGENTS.atelier.md": render_host_surface(
            ROOT / "integrations/antigravity/AGENTS.atelier.md",
            title="Atelier - Antigravity Agent",
            host="antigravity",
        ),
        ROOT
        / "integrations/opencode/agents/atelier.md": render_host_surface(
            ROOT / "integrations/opencode/agents/atelier.md",
            title="atelier:code",
            host="opencode",
        ),
        ROOT
        / "integrations/cursor/AGENTS.atelier.md": render_host_surface(
            ROOT / "integrations/cursor/AGENTS.atelier.md",
            title="Atelier - Cursor Agent",
            host="cursor",
        ),
        ROOT / "integrations/cursor/rules/coding-guidelines.mdc": render_cursor_coding_rules(),
        ROOT
        / "integrations/hermes/AGENTS.atelier.md": render_host_surface(
            ROOT / "integrations/hermes/AGENTS.atelier.md",
            title="Atelier - Hermes Agent",
            host="hermes",
        ),
    }
    for role_id in registry.surfaced_role_ids("copilot_agent"):
        projection = registry.projection(role_id, "copilot_agent")
        integration_path = ROOT / "integrations" / "copilot" / "agents" / f"{projection.output_name}.agent.md"
        outputs[ROOT / ".github" / "agents" / f"{projection.output_name}.agent.md"] = rewrite_agent_model(
            mode_outputs[integration_path],
            resolve_host_model("copilot", role_id, workspace_root=ROOT, fallback=CANONICAL_COPILOT_AGENT_MODEL),
        )
    outputs.update(mode_outputs)
    outputs.update(sync_host_configs())
    return outputs


def write_or_diff(path: Path, expected: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == expected:
        return False
    if check:
        diff = difflib.unified_diff(
            current.splitlines(),
            expected.splitlines(),
            fromfile=str(path),
            tofile=f"{path} (generated)",
            lineterm="",
        )
        sys.stdout.write("\n".join(diff) + "\n")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files differ from checked-in copies")
    args = parser.parse_args()

    changed = False
    for path, content in build_outputs().items():
        changed = write_or_diff(path, content, check=args.check) or changed

    if args.check and changed:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
